#!/bin/bash
## create view only API Key in grafana, and add that to APIKEY variable!


set -o errexit
set -o pipefail
set -x

HOST="ubuntu"
PORT=":3000"	#if no need, then leave it empty
APIKEY="eyJrIjoiSWtVRHF2QjJGRGtVMkMxOW53UTJ6elYzM3RlekxDeGoiLCJuIjoiYWRtaW4iLCJpZCI6MX0="
USER="admin"
PASS="admin"
FULLURL="$USER:$PASS@$HOST$PORT"
DIR="dashboards-$HOST"

set -o nounset

echo "Exporting Grafana dashboards from $HOST"
mkdir -p $DIR 
for dash in $(curl -H "Authorization: Bearer $APIKEY" "$FULLURL/api/search?query=&" | jq -r '.[] | select(.type == "dash-db") | .uid'); do
        curl -kH "Authorization: Bearer $APIKEY"  "$FULLURL/api/dashboards/uid/$dash" | jq -r {meta:.meta}+.dashboard > $DIR/${dash}.json 
        slug=$(cat $DIR/${dash}.json | jq -r '.meta.slug')
        mv $DIR/${dash}.json $DIR/${dash}-${slug}.json
done
